import { EmbedOptions, EventNameMap, OptionNames } from './types'

export const VIMEO_TO_REACT_EVENT_NAMES_MAP: EventNameMap = {
  play: 'onPlay',
  playing: 'onPlaying',
  pause: 'onPause',
  ended: 'onEnd',
  timeupdate: 'onTimeUpdate',
  progress: 'onProgress',
  seeked: 'onSeeked',
  texttrackchange: 'onTextTrackChange',
  cuechange: 'onCueChange',
  cuepoint: 'onCuePoint',
  volumechange: 'onVolumeChange',
  playbackratechange: 'onPlaybackRateChange',
  error: 'onError',
  loaded: 'onLoaded',
}

export const OPTIONS_NAMES: OptionNames = {
  autopause: 'autopause',
  autopip: 'autopip',
  autoplay: 'autoplay',
  background: 'background',
  showByline: 'showByline',
  color: 'color',
  colors: 'colors',
  controls: 'controls',
  dnt: 'dnt',
  height: 'height',
  interactiveParams: 'interactiveParams',
  keyboard: 'keyboard',
  loop: 'loop',
  maxHeight: 'maxHeight',
  maxWidth: 'maxWidth',
  muted: 'muted',
  pip: 'pip',
  playsInline: 'playsInline',
  showPortrait: 'showPortrait',
  quality: 'quality',
  responsive: 'responsive',
  speed: 'speed',
  start: 'start',
  textTrack: 'textTrack',
  title: 'title',
  transparent: 'transparent',
  volume: 'volume',
  width: 'width',
}

export const EMBED_OPTIONS_DEFAULT_VALUES: EmbedOptions = {
  [OPTIONS_NAMES.autopause]: true,
  [OPTIONS_NAMES.autopip]: null,
  [OPTIONS_NAMES.autoplay]: false,
  [OPTIONS_NAMES.background]: false,
  [OPTIONS_NAMES.showByline]: true,
  [OPTIONS_NAMES.color]: null,
  [OPTIONS_NAMES.colors]: null,
  [OPTIONS_NAMES.controls]: true,
  [OPTIONS_NAMES.dnt]: false,
  [OPTIONS_NAMES.height]: null,
  [OPTIONS_NAMES.interactiveParams]: null,
  [OPTIONS_NAMES.keyboard]: true,
  [OPTIONS_NAMES.loop]: false,
  [OPTIONS_NAMES.maxHeight]: null,
  [OPTIONS_NAMES.maxWidth]: null,
  [OPTIONS_NAMES.muted]: false,
  [OPTIONS_NAMES.pip]: null,
  [OPTIONS_NAMES.playsInline]: true,
  [OPTIONS_NAMES.showPortrait]: true,
  [OPTIONS_NAMES.quality]: 'auto',
  [OPTIONS_NAMES.responsive]: false,
  [OPTIONS_NAMES.speed]: false,
  [OPTIONS_NAMES.textTrack]: null,
  [OPTIONS_NAMES.title]: true,
  [OPTIONS_NAMES.transparent]: true,
  [OPTIONS_NAMES.width]: null,
}
